### ISSUE TITLE
System-availability by week

### ISSUE THREAD

**Issue by juhapekkaeloranta** [citybike-statistics/citybike-statistics.github.io#5]
See issue #3

**Comment by lauranor** [comment]
@juhapekkamoilanen onko ok nyt?

**Comment by juhapekkaeloranta** [comment]
Joo on! Korjasin vielä sen plotin otsikon: https://github.com/citybike-data-vis/bike-data-vis/commit/3faf7e17364f161c36591a385dbcb4db34162718
